import type { TechniqueDef } from '@/systems/techniques';

/** Clan techniques: only members of the clan can learn them. */
export const CLAN_TECHNIQUES: readonly TechniqueDef[] = [
  {
    id: 'hibana-spark',
    name: 'Kiln Spark',
    description: 'A snap of the fingers and a spit of flame, the first thing every Hibana learns.',
    discipline: 'ninjutsu',
    element: 'fire',
    effect: 'damage',
    chakraCost: 6,
    power: 10,
    requirements: {},
    difficulty: 30,
    clan: 'hibana',
  },
  {
    id: 'hibana-wildfire',
    name: 'Lantern Wildfire',
    description: 'Every lantern on the street flares at once, and the fire leaps.',
    discipline: 'ninjutsu',
    element: 'fire',
    effect: 'damage',
    chakraCost: 14,
    power: 20,
    requirements: { ninjutsu: 12 },
    difficulty: 85,
    clan: 'hibana',
  },
  {
    id: 'guiding-light',
    name: 'Guiding Light',
    description: 'A lantern-light that leads the enemy’s eyes wherever you want.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 8,
    power: 10,
    requirements: {},
    difficulty: 30,
    clan: 'tokaku',
  },
  {
    id: 'lantern-procession',
    name: 'Lantern Procession',
    description: 'The dead walk past the enemy, one by one, and each one looks at them.',
    discipline: 'genjutsu',
    effect: 'damage',
    chakraCost: 12,
    power: 16,
    requirements: { genjutsu: 11, willpower: 9 },
    difficulty: 70,
    clan: 'tokaku',
  },
  {
    id: 'forge-cut',
    name: 'Forge Cut',
    description: 'A heavy downward stroke, struck like a hammer on an anvil.',
    discipline: 'kenjutsu',
    effect: 'damage',
    chakraCost: 5,
    power: 13,
    requirements: {},
    difficulty: 35,
    clan: 'kurogane',
  },
  {
    id: 'tempered-edge',
    name: 'Tempered Edge',
    description: 'Chakra folded into the blade a hundred times. It cuts through anything.',
    discipline: 'kenjutsu',
    effect: 'damage',
    chakraCost: 10,
    power: 20,
    requirements: { kenjutsu: 12, strength: 10 },
    difficulty: 80,
    clan: 'kurogane',
  },
  {
    id: 'binding-rope',
    name: 'Binding Rope',
    description: 'A sacred rope of chakra that wraps the enemy’s flow tight.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 8,
    power: 10,
    requirements: {},
    difficulty: 35,
    clan: 'shimenawa',
  },
  {
    id: 'sacred-rope-ward',
    name: 'Sacred Rope Ward',
    description: 'The rope that holds the dead in their graves, wound around the living.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 14,
    power: 16,
    requirements: { fuuinjutsu: 13 },
    difficulty: 90,
    clan: 'shimenawa',
  },
];
