import type { EnemyDef } from '../../types';

export const ENEMIES: readonly EnemyDef[] = [
  {
    id: 'feral-tanuki',
    kind: 'Beast',
    name: 'Feral Tanuki',
    description: 'Fat, furious, and far quicker than it looks.',
    baseStat: 3,
    statBonuses: { speed: 3, strength: 1 },
    maxHealth: 40,
    maxChakra: 0,
    techniqueIds: [],
    traits: ['swift', 'coward'],
  },
  {
    id: 'bandit-thug',
    kind: 'Bandit',
    name: 'Bandit Thug',
    description: 'A road-bandit with a club and no patience.',
    baseStat: 5,
    statBonuses: { strength: 2, taijutsu: 1 },
    maxHealth: 60,
    maxChakra: 10,
    techniqueIds: [],
    traits: ['brawler'],
  },
  {
    id: 'academy-dropout',
    kind: 'Rogue',
    name: 'Academy Dropout',
    description: 'Washed out of the academy two years ago and bitter about it.',
    baseStat: 6,
    statBonuses: { ninjutsu: 1 },
    maxHealth: 65,
    maxChakra: 40,
    techniqueIds: ['palm-strike', 'pebble-volley'],
    traits: ['coward'],
    nature: 'earth',
  },
  {
    id: 'storehouse-wraith',
    kind: 'Spirit',
    name: 'Storehouse Wraith',
    description: 'The cold remnant of a merchant who died counting his rice.',
    baseStat: 6,
    statBonuses: { genjutsu: 3, willpower: 3, stamina: -2 },
    maxHealth: 55,
    maxChakra: 40,
    techniqueIds: ['shadow-feint', 'whispering-dread'],
    traits: ['spirit', 'illusionist'],
  },
  {
    id: 'bandit-chief',
    kind: 'Bandit',
    name: 'Bandit Chief',
    description: 'Ran away from a ninja academy once. Learned just enough to be dangerous.',
    baseStat: 8,
    statBonuses: { strength: 2, taijutsu: 2, stamina: 2 },
    maxHealth: 95,
    maxChakra: 30,
    techniqueIds: ['palm-strike', 'crescent-drop'],
    traits: ['armoured'],
  },
  {
    id: 'hungry-ghost',
    kind: 'Spirit',
    name: 'Hungry Ghost',
    description: 'A festival-goer nobody remembered to light a lantern for.',
    baseStat: 7,
    statBonuses: { genjutsu: 3, willpower: 2, stamina: -1 },
    maxHealth: 60,
    maxChakra: 45,
    techniqueIds: ['whispering-dread', 'shadow-feint'],
    traits: ['spirit'],
  },
  {
    id: 'bandit-archer',
    kind: 'Bandit',
    name: 'Bandit Archer',
    description: 'Shoots from the treeline and runs the moment anyone gets close.',
    baseStat: 5,
    statBonuses: { speed: 2, perception: 2, strength: -1 },
    maxHealth: 50,
    maxChakra: 10,
    techniqueIds: [],
    traits: ['archer', 'coward'],
  },
];
