import type { FoodDef } from '../../types';

export const FOODS: readonly FoodDef[] = [
  {
    id: 'rice-ball',
    icon: 'rice',
    name: 'Rice Ball',
    description: 'Wrapped in seaweed, eaten on the run.',
    cost: 15,
    satiety: 20,
    energy: 0,
    slots: 0,
  },
  {
    id: 'grilled-fish',
    icon: 'fish',
    name: 'Grilled River Fish',
    description: 'Salted and charred over the stall’s coals.',
    cost: 30,
    satiety: 35,
    energy: 0,
    slots: 0,
  },
  {
    id: 'ember-noodles',
    icon: 'bowl',
    name: 'Ember Noodles',
    description: 'A fiery broth the whole village swears by.',
    cost: 45,
    satiety: 50,
    energy: 5,
    slots: 0,
  },
  {
    id: 'soldier-pill',
    icon: 'pill',
    name: 'Soldier Pill',
    description: 'Bitter, chalky, and it makes your heart race.',
    cost: 40,
    satiety: 10,
    energy: 30,
    slots: 0,
  },
  {
    id: 'teahouse-feast',
    icon: 'tea',
    name: 'Teahouse Feast',
    description: 'A long, unhurried meal by the lantern canal.',
    cost: 90,
    satiety: 80,
    energy: 20,
    slots: 1,
  },
  {
    id: 'kite-candy',
    icon: 'dango',
    name: 'Kite Candy',
    description: 'Spun sugar shaped like a paper kite. Gone in three bites.',
    cost: 8,
    satiety: 10,
    energy: 15,
    slots: 0,
  },
  {
    id: 'spark-squid',
    icon: 'fish',
    name: 'Fire-Roasted Squid',
    description: 'Grilled over a Hibana flame until the edges crackle.',
    cost: 20,
    satiety: 30,
    energy: 10,
    slots: 0,
  },
  {
    id: 'lantern-dango',
    icon: 'dango',
    name: 'Lantern Dango',
    description: 'Three glowing-orange dumplings on a stick, one for each lantern you light.',
    cost: 12,
    satiety: 20,
    energy: 15,
    slots: 0,
  },
  {
    id: 'festival-takoyaki',
    icon: 'bowl',
    name: 'Festival Takoyaki',
    description: 'Molten octopus balls that burn your tongue every single time.',
    cost: 18,
    satiety: 30,
    energy: 10,
    slots: 0,
  },
  {
    id: 'vigil-soup',
    icon: 'bowl',
    name: 'Brazier Soup',
    description: 'Ginger broth ladled out to everyone keeping the long watch.',
    cost: 10,
    satiety: 30,
    energy: 20,
    slots: 0,
  },
];
