import type { GearDef } from '../../types';

/** What the forge and the outfitter sell. Bonuses apply in fights while equipped. */
export const GEAR: readonly GearDef[] = [
  {
    id: 'wrapped-knuckles',
    name: 'Wrapped Knuckles',
    description: 'Cloth and leather over the fists. Every brawler’s first purchase.',
    slot: 'weapon',
    cost: 120,
    icon: 'fist',
    statBonuses: { taijutsu: 2 },
  },
  {
    id: 'lantern-steel-tanto',
    name: 'Lantern-Steel Tantō',
    description: 'A short blade folded in the same forge that makes the lantern hooks.',
    slot: 'weapon',
    cost: 180,
    icon: 'sword',
    statBonuses: { kenjutsu: 2, speed: 1 },
  },
  {
    id: 'ash-ink-brush',
    name: 'Ash-Ink Sealing Brush',
    description: 'Ink ground from lantern ash. Seals written with it hold a little longer.',
    slot: 'weapon',
    cost: 200,
    icon: 'seal',
    statBonuses: { fuuinjutsu: 3 },
  },
  {
    id: 'focusing-bell',
    name: 'Focusing Bell',
    description: 'A tiny bell whose ring slips into the listener’s mind.',
    slot: 'weapon',
    cost: 200,
    icon: 'charm',
    statBonuses: { genjutsu: 2, perception: 1 },
  },
  {
    id: 'ember-gauntlets',
    name: 'Ember Gauntlets',
    description: 'Iron plates etched with fire seals. They warm when you mould chakra.',
    slot: 'weapon',
    cost: 300,
    icon: 'fist',
    statBonuses: { taijutsu: 2, ninjutsu: 2 },
  },
  {
    id: 'kurogane-katana',
    name: 'Kurogane Katana',
    description: 'A clan smith’s blade. Expensive, and worth every ryo.',
    slot: 'weapon',
    cost: 380,
    icon: 'sword',
    statBonuses: { kenjutsu: 3, strength: 1 },
  },
  {
    id: 'padded-jacket',
    name: 'Padded Jacket',
    description: 'Quilted cotton. Turns a scrape into a bruise.',
    slot: 'body',
    cost: 90,
    icon: 'vest',
    statBonuses: { stamina: 1 },
  },
  {
    id: 'shadow-garb',
    name: 'Shadow Garb',
    description: 'Dark, close-fitting, silent. Made for night patrols.',
    slot: 'body',
    cost: 240,
    icon: 'vest',
    statBonuses: { speed: 2, perception: 1 },
  },
  {
    id: 'flak-vest',
    name: 'Flak Vest',
    description: 'Plated pockets for scrolls and kunai, and for stopping blades.',
    slot: 'body',
    cost: 260,
    icon: 'vest',
    statBonuses: { stamina: 3 },
  },
  {
    id: 'lantern-charm',
    name: 'Lantern Charm',
    description: 'A paper lantern no bigger than a thumb. The restless dead keep their distance.',
    slot: 'charm',
    cost: 150,
    icon: 'lantern',
    statBonuses: { willpower: 2 },
  },
  {
    id: 'hawk-talisman',
    name: 'Hawk-Eye Talisman',
    description: 'A feather bound in red thread. You notice things a moment sooner.',
    slot: 'charm',
    cost: 180,
    icon: 'eye',
    statBonuses: { perception: 2 },
  },
  {
    id: 'chakra-beads',
    name: 'Chakra Beads',
    description: 'Prayer beads that hum when your chakra wanders.',
    slot: 'charm',
    cost: 220,
    icon: 'charm',
    statBonuses: { chakraControl: 2 },
  },
];
