import { look } from '../../look';
import type { PersonDef } from '../../types';

/** The genin of your graduating year. Friends, rivals, nuisances. */
export const GENIN: readonly PersonDef[] = [
  {
    id: 'kaen',
    name: 'Kaen',
    familyName: 'Hibana',
    role: 'genin',
    title: 'Genin',
    clanId: 'hibana',
    traitIds: ['brash', 'proud'],
    appearance: look('spiky', {
      hair: '#b8322c',
      eyes: '#c88a2a',
      skin: '#e2b48c',
      outfit: '#e8823a',
    }),
    specialty: 'ninjutsu',
    bio: 'Burned the Academy roof down twice. Says the second time was on purpose.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'mission-hall',
      evening: 'market-street',
      night: null,
    },
  },
  {
    id: 'shiori',
    name: 'Shiori',
    familyName: 'Tōkaku',
    role: 'genin',
    title: 'Genin',
    clanId: 'tokaku',
    traitIds: ['calm', 'kind'],
    appearance: look('long', {
      hair: '#e8e0d0',
      eyes: '#8ab4d8',
      skin: '#f3d2b3',
      outfit: '#3a3a5e',
    }),
    specialty: 'genjutsu',
    bio: 'Waves at empty corners. Leaves rice out for someone called "Grandfather".',
    schedule: { morning: 'academy', afternoon: 'training-grounds', evening: null, night: null },
  },
  {
    id: 'jin',
    name: 'Jin',
    familyName: 'Kurogane',
    role: 'genin',
    title: 'Genin',
    clanId: 'kurogane',
    traitIds: ['focused', 'proud'],
    appearance: look(
      'short',
      { hair: '#1b1a22', eyes: '#2a1d14', skin: '#c68e63', outfit: '#3e4a52' },
      'belt',
    ),
    specialty: 'kenjutsu',
    bio: 'Top of the class. Sleeps with his sword. Has not smiled since he was nine.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'training-grounds',
      evening: 'market-street',
      night: null,
    },
  },
  {
    id: 'nao',
    name: 'Nao',
    familyName: 'Shimenawa',
    role: 'genin',
    title: 'Genin',
    clanId: 'shimenawa',
    traitIds: ['humble', 'diligent'],
    appearance: look(
      'buns',
      { hair: '#4a2f1d', eyes: '#5a7a4a', skin: '#f3d2b3', outfit: '#e8e0d0' },
      'neck',
    ),
    specialty: 'fuuinjutsu',
    bio: 'Frail, sharp, and always writing. Her seals are better than some jōnin’s.',
    schedule: {
      morning: 'academy',
      afternoon: 'mission-hall',
      evening: 'market-street',
      night: null,
    },
  },
  {
    id: 'kenji',
    name: 'Kenji',
    familyName: 'Oda',
    role: 'genin',
    title: 'Genin',
    traitIds: ['lazy', 'cunning'],
    appearance: look(
      'short',
      { hair: '#4a2f1d', eyes: '#2a1d14', skin: '#e2b48c', outfit: '#3e6b3a' },
      'arm',
    ),
    specialty: 'taijutsu',
    bio: 'Passed the final exam by being asleep in the right place. Nobody knows how.',
    schedule: { morning: null, afternoon: 'market-street', evening: 'market-street', night: null },
  },
  {
    id: 'mio',
    name: 'Mio',
    familyName: 'Sakai',
    role: 'genin',
    title: 'Genin',
    traitIds: ['curious', 'kind'],
    appearance: look('ponytail', {
      hair: '#8a5a2b',
      eyes: '#3b6fb6',
      skin: '#f3d2b3',
      outfit: '#2f4f7a',
    }),
    specialty: 'taijutsu',
    bio: 'Asks a question about everything. Has a notebook of the answers.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'academy',
      evening: 'market-street',
      night: null,
    },
  },
];
