import { allDay, look } from '../../look';
import type { PersonDef } from '../../types';

/** Jōnin who may take on a team, plus the village figures every genin knows. */
export const SENSEIS_AND_ELDERS: readonly PersonDef[] = [
  {
    id: 'goran',
    name: 'Gōran',
    familyName: 'Ishizaki',
    role: 'sensei',
    title: 'Jōnin',
    traitIds: ['brash', 'diligent'],
    appearance: look(
      'shaved',
      { hair: '#1b1a22', eyes: '#2a1d14', skin: '#a8714c', outfit: '#7a3b2a' },
      'arm',
    ),
    specialty: 'taijutsu',
    bio: 'Broke a mountain bandit’s blade with his forearm. Has the scar to prove it, and shows everyone.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'training-grounds',
      evening: 'market-street',
      night: null,
    },
    sensei: {
      specialty: 'taijutsu',
      favouredTraits: ['brash', 'diligent', 'proud'],
      style: 'Up before dawn, running stairs until you can’t feel your legs. Loud about it.',
      lesson: 'Gōran has you hit the striking post until it splinters, then hands you a new one.',
      teaches: ['iron-gate-palm'],
    },
  },
  {
    id: 'akari',
    name: 'Akari',
    familyName: 'Hibana',
    role: 'sensei',
    title: 'Jōnin',
    clanId: 'hibana',
    traitIds: ['proud', 'curious'],
    appearance: look('ponytail', {
      hair: '#b8322c',
      eyes: '#c88a2a',
      skin: '#e2b48c',
      outfit: '#2a2a32',
    }),
    specialty: 'ninjutsu',
    bio: 'Lights the great lantern at the village gate every dusk. Has never once needed a match.',
    schedule: {
      morning: 'academy',
      afternoon: 'mission-hall',
      evening: 'training-grounds',
      night: null,
    },
    sensei: {
      specialty: 'ninjutsu',
      favouredTraits: ['proud', 'curious', 'brash'],
      nature: 'fire',
      style: 'Demanding and dazzling. Expects you to burn as bright as she does.',
      lesson:
        'Akari makes you hold a flame in your palm until it stops flickering. It takes all afternoon.',
      teaches: ['great-lantern-flame'],
    },
  },
  {
    id: 'yomi',
    name: 'Yomi',
    familyName: 'Tōkaku',
    role: 'sensei',
    title: 'Jōnin',
    clanId: 'tokaku',
    traitIds: ['calm', 'curious'],
    appearance: look('long', {
      hair: '#e8e0d0',
      eyes: '#8ab4d8',
      skin: '#f3d2b3',
      outfit: '#3a3a5e',
    }),
    specialty: 'genjutsu',
    bio: 'Talks to people nobody else can see. Usually they answer.',
    schedule: { morning: null, afternoon: 'academy', evening: 'mission-hall', night: null },
    sensei: {
      specialty: 'genjutsu',
      favouredTraits: ['calm', 'curious', 'humble'],
      nature: 'water',
      style: 'Soft-spoken and strange. Teaches you to notice what you were not meant to.',
      lesson:
        'Yomi has you sit among the grave lanterns until you can tell which lights are lit by the living.',
      teaches: ['ghost-lantern-veil'],
    },
  },
  {
    id: 'tetsu',
    name: 'Tetsu',
    familyName: 'Kurogane',
    role: 'sensei',
    title: 'Jōnin',
    clanId: 'kurogane',
    traitIds: ['focused', 'humble'],
    appearance: look(
      'short',
      { hair: '#3a3a42', eyes: '#2a1d14', skin: '#c68e63', outfit: '#3e4a52' },
      'belt',
    ),
    specialty: 'kenjutsu',
    bio: 'Forged the Tōrokage’s sword. Says almost nothing; his blade says the rest.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'market-street',
      evening: null,
      night: null,
    },
    sensei: {
      specialty: 'kenjutsu',
      favouredTraits: ['focused', 'humble', 'calm'],
      nature: 'earth',
      style: 'A thousand cuts a day, each one perfect. Silence is praise.',
      lesson: 'Tetsu watches you cut a thousand times and says one word. It is the right word.',
      teaches: ['forge-flash-cut'],
    },
  },
  {
    id: 'ito',
    name: 'Ito',
    familyName: 'Shimenawa',
    role: 'sensei',
    title: 'Special Jōnin',
    clanId: 'shimenawa',
    traitIds: ['cunning', 'diligent'],
    appearance: look(
      'buns',
      { hair: '#4a2f1d', eyes: '#5a7a4a', skin: '#f3d2b3', outfit: '#e8e0d0' },
      'neck',
    ),
    specialty: 'fuuinjutsu',
    bio: 'Weaves the ropes that hold the restless dead. Keeps a seal for every occasion.',
    schedule: {
      morning: 'mission-hall',
      afternoon: 'academy',
      evening: 'market-street',
      night: null,
    },
    sensei: {
      specialty: 'fuuinjutsu',
      favouredTraits: ['cunning', 'diligent', 'focused'],
      nature: 'wind',
      style: 'Patient, precise, and always three moves ahead. Loves a good trap.',
      lesson:
        'Ito sets traps around the training ground and makes you write a ward for each before dark.',
      teaches: ['shrine-rope-binding'],
    },
  },
  {
    id: 'rin',
    name: 'Rin',
    familyName: 'Asagiri',
    role: 'instructor',
    title: 'Academy instructor',
    traitIds: ['kind', 'diligent'],
    appearance: look('ponytail', {
      hair: '#1b1a22',
      eyes: '#2a1d14',
      skin: '#e2b48c',
      outfit: '#7a3b2a',
    }),
    bio: 'Caught you reading your own file and let you off. Hands out jobs in the afternoons.',
    schedule: {
      morning: 'academy',
      afternoon: 'mission-hall',
      evening: 'market-street',
      night: null,
    },
  },
  {
    id: 'torokage',
    name: 'Hoshi',
    familyName: 'Kagari',
    role: 'leader',
    title: 'Tōrokage',
    traitIds: ['calm', 'kind'],
    appearance: look(
      'long',
      { hair: '#e8e0d0', eyes: '#2a1d14', skin: '#c68e63', outfit: '#b8322c' },
      'arm',
    ),
    bio: 'The Old Lamp. Has led the village through two wars and a very long winter.',
    schedule: { morning: 'mission-hall', afternoon: null, evening: null, night: null },
  },
  {
    id: 'tsune',
    name: 'Tsune',
    familyName: '',
    role: 'villager',
    title: 'Noodle-stall owner',
    traitIds: ['kind', 'cunning'],
    appearance: look(
      'buns',
      { hair: '#e8e0d0', eyes: '#2a1d14', skin: '#e2b48c', outfit: '#3e6b3a' },
      'arm',
    ),
    bio: 'Granny Tsune has fed three generations of shinobi. Remembers every one who never paid.',
    schedule: allDay('market-street'),
  },
];
