import type { TechniqueDef } from '@/systems/techniques';

/** Signature techniques only a sensei can teach, at their weekly lessons. */
export const SENSEI_TECHNIQUES: readonly TechniqueDef[] = [
  {
    id: 'iron-gate-palm',
    name: 'Iron Gate Palm',
    description: 'One step, one palm, all your weight behind it. Doors have been known to give.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 8,
    power: 20,
    requirements: {},
    difficulty: 60,
  },
  {
    id: 'great-lantern-flame',
    name: 'Great Lantern Flame',
    description: 'The flame that lights the village gate, aimed somewhere less friendly.',
    discipline: 'ninjutsu',
    element: 'fire',
    effect: 'damage',
    chakraCost: 14,
    power: 23,
    requirements: {},
    difficulty: 80,
  },
  {
    id: 'ghost-lantern-veil',
    name: 'Ghost Lantern Veil',
    description: 'The target sees the dead walking toward them, lanterns in hand.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 12,
    power: 18,
    requirements: {},
    difficulty: 70,
  },
  {
    id: 'forge-flash-cut',
    name: 'Forge-Flash Cut',
    description: 'A draw so fast the blade glows like it has just left the fire.',
    discipline: 'kenjutsu',
    element: 'earth',
    effect: 'damage',
    chakraCost: 10,
    power: 21,
    requirements: {},
    difficulty: 70,
  },
  {
    id: 'shrine-rope-binding',
    name: 'Shrine Rope Binding',
    description: 'Sacred rope lashes out and ties the target’s chakra in knots.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 12,
    power: 16,
    requirements: {},
    difficulty: 70,
  },
];
