import type { TechniqueDef } from '@/systems/techniques';

export const TECHNIQUES: readonly TechniqueDef[] = [
  {
    id: 'palm-strike',
    name: 'Palm Strike',
    description: 'A chakra-backed open palm, the first technique every academy student learns.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 3,
    power: 8,
    requirements: {},
    difficulty: 20,
  },
  {
    id: 'shadow-feint',
    name: 'Shadow Feint',
    description: 'A flicker of false movement that leaves the target swiping at nothing.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 6,
    power: 6,
    requirements: {},
    difficulty: 20,
  },
  {
    id: 'gale-heel',
    name: 'Gale Heel',
    description: 'A spinning kick riding a gust of wind chakra.',
    discipline: 'taijutsu',
    element: 'wind',
    effect: 'damage',
    chakraCost: 5,
    power: 13,
    requirements: { taijutsu: 8, speed: 7 },
    difficulty: 40,
  },
  {
    id: 'pebble-volley',
    name: 'Pebble Volley',
    description: 'Tear stones from the ground and hurl them in a stinging spray.',
    discipline: 'ninjutsu',
    element: 'earth',
    effect: 'damage',
    chakraCost: 8,
    power: 12,
    requirements: { ninjutsu: 7 },
    difficulty: 40,
  },
  {
    id: 'lantern-mirage',
    name: 'Lantern Mirage',
    description: 'Dozens of drifting lantern-lights crowd the target’s vision.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 10,
    power: 12,
    requirements: { genjutsu: 8, perception: 6 },
    difficulty: 45,
  },
  {
    id: 'crescent-drop',
    name: 'Crescent Drop',
    description: 'Leap, flip, and bring the heel down like a falling moon.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 7,
    power: 18,
    requirements: { taijutsu: 12, strength: 10 },
    difficulty: 70,
  },
  {
    id: 'ember-breath',
    name: 'Ember Breath',
    description: 'Mould chakra into the lungs and exhale a gout of embers.',
    discipline: 'ninjutsu',
    element: 'fire',
    effect: 'damage',
    chakraCost: 12,
    power: 18,
    requirements: { ninjutsu: 10, chakraControl: 8 },
    difficulty: 70,
  },
  {
    id: 'tide-lash',
    name: 'Tide Lash',
    description: 'Draw moisture from the air into a whip of pressurised water.',
    discipline: 'ninjutsu',
    element: 'water',
    effect: 'damage',
    chakraCost: 15,
    power: 22,
    requirements: { ninjutsu: 13, chakraControl: 11 },
    difficulty: 90,
  },
  {
    id: 'whispering-dread',
    name: 'Whispering Dread',
    description: 'Let the target hear what the restless dead whisper. The mind wounds the body.',
    discipline: 'genjutsu',
    effect: 'damage',
    chakraCost: 11,
    power: 16,
    requirements: { genjutsu: 11, willpower: 9 },
    difficulty: 75,
  },
  {
    id: 'mending-glow',
    name: 'Mending Glow',
    description: 'A warm lantern-light chakra that knits shallow wounds.',
    discipline: 'ninjutsu',
    effect: 'heal',
    chakraCost: 12,
    power: 18,
    requirements: { chakraControl: 9, intellect: 8 },
    difficulty: 60,
  },
  {
    id: 'lantern-cut',
    name: 'Lantern Cut',
    description: 'A rising cut that snuffs a lantern flame without touching the paper.',
    discipline: 'kenjutsu',
    effect: 'damage',
    chakraCost: 4,
    power: 12,
    requirements: { kenjutsu: 7 },
    difficulty: 40,
  },
  {
    id: 'moonfall-slash',
    name: 'Moonfall Slash',
    description: 'Leap high, and come down with the whole weight of the night.',
    discipline: 'kenjutsu',
    effect: 'damage',
    chakraCost: 10,
    power: 20,
    requirements: { kenjutsu: 12, speed: 10 },
    difficulty: 80,
  },
  {
    id: 'ember-tag',
    name: 'Ember Tag',
    description: 'A paper seal that bursts into flame on contact.',
    discipline: 'fuuinjutsu',
    effect: 'damage',
    chakraCost: 6,
    power: 12,
    requirements: { fuuinjutsu: 7 },
    difficulty: 40,
  },
  {
    id: 'binding-ward',
    name: 'Binding Ward',
    description: 'A ward slapped onto the enemy. Their chakra stops answering.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 9,
    power: 10,
    requirements: { fuuinjutsu: 9 },
    difficulty: 55,
  },
  {
    id: 'great-seal-of-ash',
    name: 'Great Seal of Ash',
    description: 'A circle of ash and ink that locks every chakra point it touches.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 14,
    power: 16,
    requirements: { fuuinjutsu: 14 },
    difficulty: 90,
  },
];
