import type { TrainingDef } from '../../types';

export const TRAINING: readonly TrainingDef[] = [
  {
    id: 'post-kicks',
    icon: 'post',
    name: 'Kicking Posts',
    spot: 'Training Ground 3',
    description: 'Hammer the old wrapped posts until your shins stop complaining.',
    slots: 1,
    energyCost: 20,
    gains: { strength: 1, taijutsu: 1.2 },
  },
  {
    id: 'rooftop-sprints',
    icon: 'house',
    name: 'Rooftop Sprints',
    spot: 'Lantern District rooftops',
    description: 'Race the lamplighters across the tiles.',
    slots: 1,
    energyCost: 20,
    gains: { speed: 1.5, stamina: 0.5 },
  },
  {
    id: 'lake-laps',
    icon: 'wave',
    name: 'Lake Laps',
    spot: 'Mirror Lake',
    description: 'Swim until your arms burn, then swim back.',
    slots: 1,
    energyCost: 25,
    gains: { stamina: 1.5, willpower: 0.5 },
  },
  {
    id: 'leaf-meditation',
    icon: 'leaf',
    name: 'Leaf Meditation',
    spot: 'Shrine steps',
    description: 'Hold a leaf to your brow with chakra alone while the incense burns down.',
    slots: 1,
    energyCost: 10,
    gains: { chakraControl: 1.5, willpower: 0.3 },
  },
  {
    id: 'seal-drills',
    icon: 'scroll',
    name: 'Hand-Seal Drills',
    spot: 'Academy yard',
    description: 'Run the twelve seals faster and faster until they blur.',
    slots: 1,
    energyCost: 15,
    gains: { ninjutsu: 1.5, chakraControl: 0.5 },
  },
  {
    id: 'library-study',
    icon: 'scroll',
    name: 'Scroll Study',
    spot: 'Academy library',
    description: 'You pore over strategy texts until the lamps burn low.',
    slots: 1,
    energyCost: 8,
    gains: { intellect: 1.5, genjutsu: 0.4 },
  },
  {
    id: 'lantern-watching',
    icon: 'eye',
    name: 'Lantern Watching',
    spot: 'Thousand Lantern Bridge',
    description: 'Track every flickering light at once. Notice which ones are not lanterns.',
    slots: 1,
    energyCost: 10,
    gains: { perception: 1.5, genjutsu: 0.8 },
  },
  {
    id: 'waterfall-endurance',
    icon: 'wave',
    name: 'Waterfall Endurance',
    spot: 'Hollow Falls',
    description: 'Sit beneath freezing water and refuse to move.',
    slots: 1,
    energyCost: 25,
    gains: { willpower: 1.5, stamina: 0.5 },
  },
  {
    id: 'dojo-sparring',
    icon: 'fist',
    name: 'Dojo Sparring',
    spot: 'Ember Fist Dojo',
    description: 'Trade blows with other Genin. Bruises guaranteed.',
    slots: 1,
    energyCost: 30,
    gains: { taijutsu: 1, speed: 0.5, strength: 0.5, perception: 0.5 },
  },
  {
    id: 'blade-forms',
    name: 'Blade Forms',
    spot: 'Kurogane forge yard',
    icon: 'sword',
    description: 'Practice forms with a blunt blade while the smiths shout corrections.',
    slots: 1,
    energyCost: 20,
    gains: { kenjutsu: 1.5, speed: 0.3 },
  },
  {
    id: 'ward-writing',
    name: 'Ward Writing',
    spot: 'Shrine steps',
    icon: 'seal',
    description: 'Copy the old wards stroke by stroke until your brush stops shaking.',
    slots: 1,
    energyCost: 10,
    gains: { fuuinjutsu: 1.5, chakraControl: 0.3 },
  },
];
