import type { TrainingDef } from './types';

export const TRAINING: readonly TrainingDef[] = [
  {
    id: 'post-kicks',
    name: 'Kicking Posts',
    location: 'Training Ground 3',
    description: 'Hammer the old wrapped posts until your shins stop complaining.',
    slots: 1,
    energyCost: 20,
    gains: { strength: 1, taijutsu: 1.2 },
  },
  {
    id: 'rooftop-sprints',
    name: 'Rooftop Sprints',
    location: 'Lantern District rooftops',
    description: 'Race the lamplighters across the tiles.',
    slots: 1,
    energyCost: 20,
    gains: { speed: 1.5, stamina: 0.5 },
  },
  {
    id: 'lake-laps',
    name: 'Lake Laps',
    location: 'Mirror Lake',
    description: 'Swim until your arms burn, then swim back.',
    slots: 1,
    energyCost: 25,
    gains: { stamina: 1.5, willpower: 0.5 },
  },
  {
    id: 'leaf-meditation',
    name: 'Leaf Meditation',
    location: 'Shrine steps',
    description: 'Hold a leaf to your brow with chakra alone while the incense burns down.',
    slots: 1,
    energyCost: 10,
    gains: { chakraControl: 1.5, willpower: 0.3 },
  },
  {
    id: 'seal-drills',
    name: 'Hand-Seal Drills',
    location: 'Academy yard',
    description: 'Run the twelve seals faster and faster until they blur.',
    slots: 1,
    energyCost: 15,
    gains: { ninjutsu: 1.5, chakraControl: 0.5 },
  },
  {
    id: 'library-study',
    name: 'Scroll Study',
    location: 'Academy library',
    description: 'Pore over strategy texts and chakra theory.',
    slots: 1,
    energyCost: 8,
    gains: { intellect: 1.5, genjutsu: 0.4 },
  },
  {
    id: 'lantern-watching',
    name: 'Lantern Watching',
    location: 'Thousand Lantern Bridge',
    description: 'Track every flickering light at once. Notice which ones are not lanterns.',
    slots: 1,
    energyCost: 10,
    gains: { perception: 1.5, genjutsu: 0.8 },
  },
  {
    id: 'waterfall-endurance',
    name: 'Waterfall Endurance',
    location: 'Hollow Falls',
    description: 'Sit beneath freezing water and refuse to move.',
    slots: 1,
    energyCost: 25,
    gains: { willpower: 1.5, stamina: 0.5 },
  },
  {
    id: 'dojo-sparring',
    name: 'Dojo Sparring',
    location: 'Ember Fist Dojo',
    description: 'Trade blows with other Genin. Bruises guaranteed.',
    slots: 1,
    energyCost: 30,
    gains: { taijutsu: 1, speed: 0.5, strength: 0.5, perception: 0.5 },
  },
];
