import type { TechniqueDef } from '@/systems/techniques';

/** Hiden techniques: only members of the clan can learn them. */
export const CLAN_TECHNIQUES: readonly TechniqueDef[] = [
  {
    id: 'great-fireball',
    name: 'Fire Style: Great Fireball',
    description: 'The Uchiha rite of passage: breathe out a roaring sphere of flame.',
    discipline: 'ninjutsu',
    element: 'fire',
    effect: 'damage',
    chakraCost: 12,
    power: 18,
    requirements: { ninjutsu: 9 },
    difficulty: 60,
    clan: 'uchiha',
  },
  {
    id: 'gentle-fist',
    name: 'Gentle Fist',
    description: 'Strike the chakra network, not the body. Points close; jutsu fail.',
    discipline: 'taijutsu',
    effect: 'seal',
    chakraCost: 4,
    power: 8,
    requirements: {},
    difficulty: 30,
    clan: 'hyuga',
  },
  {
    id: 'sixty-four-palms',
    name: 'Eight Trigrams Sixty-Four Palms',
    description: 'Sixty-four strikes in a heartbeat. Every chakra point, closed.',
    discipline: 'taijutsu',
    effect: 'seal',
    chakraCost: 10,
    power: 14,
    requirements: { taijutsu: 12, perception: 10 },
    difficulty: 80,
    clan: 'hyuga',
  },
  {
    id: 'shadow-possession',
    name: 'Shadow Possession Jutsu',
    description: 'Stretch your shadow to theirs. Where you move, they move.',
    discipline: 'ninjutsu',
    effect: 'stun',
    chakraCost: 10,
    power: 12,
    requirements: {},
    difficulty: 40,
    clan: 'nara',
  },
  {
    id: 'shadow-neck-bind',
    name: 'Shadow Neck Bind',
    description: 'The shadow climbs. Hands of darkness close around the throat.',
    discipline: 'ninjutsu',
    effect: 'damage',
    chakraCost: 12,
    power: 16,
    requirements: { ninjutsu: 10, intellect: 10 },
    difficulty: 70,
    clan: 'nara',
  },
  {
    id: 'partial-expansion',
    name: 'Partial Expansion',
    description: 'One fist swells to the size of a cart, and comes down on the enemy.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 6,
    power: 14,
    requirements: {},
    difficulty: 40,
    clan: 'akimichi',
  },
  {
    id: 'human-bullet-tank',
    name: 'Human Bullet Tank',
    description: 'Expand, tuck, and roll over everything in your path.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 10,
    power: 20,
    requirements: { taijutsu: 11, strength: 10 },
    difficulty: 75,
    clan: 'akimichi',
  },
  {
    id: 'mind-body-switch',
    name: 'Mind Body Switch',
    description: 'Throw your mind into theirs. For a moment their body is yours.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 10,
    power: 12,
    requirements: {},
    difficulty: 40,
    clan: 'yamanaka',
  },
  {
    id: 'mind-destruction',
    name: 'Mind Destruction',
    description: 'Shatter their focus from the inside.',
    discipline: 'genjutsu',
    effect: 'damage',
    chakraCost: 12,
    power: 16,
    requirements: { genjutsu: 11, willpower: 9 },
    difficulty: 70,
    clan: 'yamanaka',
  },
  {
    id: 'insect-swarm',
    name: 'Parasitic Insect Swarm',
    description: 'A black cloud pours from your sleeves and bites.',
    discipline: 'ninjutsu',
    effect: 'damage',
    chakraCost: 5,
    power: 10,
    requirements: {},
    difficulty: 30,
    clan: 'aburame',
  },
  {
    id: 'insect-jar',
    name: 'Insect Jar',
    description: 'The swarm settles on the enemy and drinks their chakra dry.',
    discipline: 'ninjutsu',
    effect: 'seal',
    chakraCost: 10,
    power: 12,
    requirements: { ninjutsu: 10, chakraControl: 9 },
    difficulty: 70,
    clan: 'aburame',
  },
  {
    id: 'fang-over-fang',
    name: 'Fang Over Fang',
    description: 'You and your ninken become two drilling whirlwinds.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 7,
    power: 14,
    requirements: {},
    difficulty: 40,
    clan: 'inuzuka',
  },
  {
    id: 'passing-fang',
    name: 'Passing Fang',
    description: 'One spinning pass, too fast to see, too fast to block.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 10,
    power: 19,
    requirements: { taijutsu: 11, speed: 10 },
    difficulty: 75,
    clan: 'inuzuka',
  },
  {
    id: 'uzumaki-chains',
    name: 'Sealing Chains',
    description: 'Chakra chains burst from your back and pin the enemy’s flow.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 8,
    power: 10,
    requirements: {},
    difficulty: 40,
    clan: 'uzumaki',
  },
  {
    id: 'adamantine-chains',
    name: 'Adamantine Sealing Chains',
    description: 'Chains that once held a tailed beast.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 14,
    power: 16,
    requirements: { fuuinjutsu: 13 },
    difficulty: 90,
    clan: 'uzumaki',
  },
];
