import type { ClanDef } from '../../types';

export const CLANS: readonly ClanDef[] = [
  {
    id: 'none',
    name: 'No clan',
    description: 'Nobody handed you anything. You train a little harder because of it.',
    statBonuses: {},
    modifiers: { training: 1.05 },
    startingTechniqueIds: [],
  },
  {
    id: 'uchiha',
    name: 'Uchiha',
    description: 'Fire, pride and a bloodline that wakes in moments of great emotion.',
    statBonuses: { ninjutsu: 2, perception: 1, willpower: -2 },
    modifiers: { studyElement: { fire: 1.3 } },
    nature: 'fire',
    startingTechniqueIds: ['phoenix-flower'],
    lodging: 'Your room in the Uchiha compound',
    kekkeiGenkai: {
      name: 'Sharingan',
      description: 'The copy wheel eye. Dormant until something awakens it.',
      dormant: true,
    },
  },
  {
    id: 'hyuga',
    name: 'Hyūga',
    description: 'The Byakugan sees chakra itself. The clan’s rules are as strict as its stance.',
    statBonuses: { perception: 3, taijutsu: 1 },
    modifiers: { studyDiscipline: { ninjutsu: 0.7 } },
    startingTechniqueIds: ['gentle-fist'],
    lodging: 'Your room in the Hyūga compound',
    kekkeiGenkai: {
      name: 'Byakugan',
      description: 'Near 360° sight that sees chakra pathways. Active from the start.',
      dormant: false,
    },
  },
  {
    id: 'nara',
    name: 'Nara',
    description: 'Shadow techniques and a mind for strategy. Not fond of effort.',
    statBonuses: { intellect: 3, stamina: -1, strength: -1 },
    modifiers: { growth: { intellect: 1.1 } },
    startingTechniqueIds: ['shadow-possession'],
    lodging: 'Your room in the Nara clan house',
  },
  {
    id: 'akimichi',
    name: 'Akimichi',
    description: 'Big bodies, bigger hearts, and an appetite to match the clan’s techniques.',
    statBonuses: { strength: 2, stamina: 2, speed: -1 },
    modifiers: { hungerRate: 1.6 },
    startingTechniqueIds: ['partial-expansion'],
    lodging: 'Your room in the Akimichi clan house',
  },
  {
    id: 'yamanaka',
    name: 'Yamanaka',
    description: 'Mind techniques, and a flower shop that hears every rumour in the village.',
    statBonuses: { genjutsu: 2, perception: 1, strength: -1 },
    modifiers: { studyDiscipline: { genjutsu: 1.2 } },
    startingTechniqueIds: ['mind-body-switch'],
    lodging: 'The room above the Yamanaka flower shop',
  },
  {
    id: 'aburame',
    name: 'Aburame',
    description: 'Your body is a hive. The insects eat chakra, yours and the enemy’s.',
    statBonuses: { chakraControl: 2, willpower: 1, speed: -1 },
    modifiers: { growth: { chakraControl: 1.1 } },
    startingTechniqueIds: ['insect-swarm'],
    lodging: 'Your room in the Aburame clan house',
  },
  {
    id: 'inuzuka',
    name: 'Inuzuka',
    description: 'Wild, loud and fast, with a nose to match your ninken.',
    statBonuses: { speed: 2, taijutsu: 1, perception: 1, intellect: -2 },
    modifiers: { growth: { speed: 1.1 } },
    startingTechniqueIds: ['fang-over-fang'],
    lodging: 'Your room in the Inuzuka kennels',
  },
  {
    id: 'uzumaki',
    name: 'Uzumaki',
    description: 'Survivors of a fallen clan of sealing masters, with enormous life force.',
    statBonuses: { stamina: 3, fuuinjutsu: 2, chakraControl: -2 },
    modifiers: { studyDiscipline: { fuuinjutsu: 1.4 } },
    startingTechniqueIds: ['uzumaki-chains'],
  },
];
