import type { EnemyDef } from '../../types';

export const ENEMIES: readonly EnemyDef[] = [
  {
    id: 'wild-boar',
    name: 'Wild Boar',
    kind: 'Beast',
    description: 'A tusked brute from the forests outside the walls.',
    baseStat: 3,
    statBonuses: { speed: 3, strength: 1 },
    maxHealth: 40,
    maxChakra: 0,
    techniqueIds: [],
    traits: ['brawler'],
  },
  {
    id: 'bandit-thug',
    name: 'Bandit Thug',
    kind: 'Bandit',
    description: 'A road-bandit with a club and no patience.',
    baseStat: 5,
    statBonuses: { strength: 2, taijutsu: 1 },
    maxHealth: 60,
    maxChakra: 10,
    techniqueIds: [],
    traits: ['brawler'],
  },
  {
    id: 'academy-dropout',
    name: 'Academy Dropout',
    kind: 'Rogue',
    description: 'Failed the graduation exam twice and blames everyone but himself.',
    baseStat: 6,
    statBonuses: { ninjutsu: 1 },
    maxHealth: 65,
    maxChakra: 40,
    techniqueIds: ['shuriken-jutsu', 'phoenix-flower'],
    traits: ['coward'],
  },
  {
    id: 'restless-spirit',
    name: 'Restless Spirit',
    kind: 'Spirit',
    description: 'The cold remnant of a merchant who died counting his grain.',
    baseStat: 6,
    statBonuses: { genjutsu: 3, willpower: 3, stamina: -2 },
    maxHealth: 55,
    maxChakra: 40,
    techniqueIds: ['clone-jutsu', 'tree-binding'],
    traits: ['spirit', 'illusionist'],
  },
  {
    id: 'bandit-chief',
    kind: 'Bandit',
    name: 'Bandit Chief',
    description: 'A hulking ex-mercenary with a chipped sword and twenty loyal thugs.',
    baseStat: 8,
    statBonuses: { strength: 2, taijutsu: 2, stamina: 2 },
    maxHealth: 95,
    maxChakra: 30,
    techniqueIds: ['shuriken-jutsu', 'leaf-whirlwind'],
    traits: ['armoured'],
  },
  {
    id: 'missing-nin',
    kind: 'Missing-nin',
    name: 'Missing-nin',
    description: 'A chūnin who fled the Hidden Mist with a slashed headband.',
    baseStat: 8,
    statBonuses: { ninjutsu: 3, speed: 2 },
    maxHealth: 80,
    maxChakra: 60,
    techniqueIds: ['water-bullet', 'shuriken-jutsu'],
    traits: ['swift'],
    nature: 'water',
  },
  {
    id: 'bandit-archer',
    kind: 'Bandit',
    name: 'Bandit Archer',
    description: 'A poacher with a hunting bow who would rather not be seen.',
    baseStat: 5,
    statBonuses: { speed: 2, perception: 2, strength: -1 },
    maxHealth: 50,
    maxChakra: 10,
    techniqueIds: [],
    traits: ['archer', 'coward'],
  },
];
