import type { FoodDef } from '../../types';

export const FOODS: readonly FoodDef[] = [
  {
    id: 'miso-ramen',
    name: 'Miso Chashu Ramen',
    icon: 'bowl',
    description: 'Teuchi’s broth has been simmering since dawn. Naruto swears by it.',
    cost: 45,
    satiety: 50,
    energy: 5,
    slots: 0,
  },
  {
    id: 'pork-ramen',
    name: 'Pork Ramen',
    icon: 'bowl',
    description: 'The plain bowl. Still better than anything you make at home.',
    cost: 30,
    satiety: 35,
    energy: 0,
    slots: 0,
  },
  {
    id: 'yakiniku',
    name: 'Yakiniku Feast',
    icon: 'grill',
    description: 'A long, smoky dinner at Yakiniku Q. Chōji would approve.',
    cost: 90,
    satiety: 80,
    energy: 20,
    slots: 1,
  },
  {
    id: 'dango',
    name: 'Dango',
    icon: 'dango',
    description: 'Three sweet dumplings on a stick, eaten on the run.',
    cost: 15,
    satiety: 20,
    energy: 0,
    slots: 0,
  },
  {
    id: 'soldier-pill',
    name: 'Soldier Pill',
    icon: 'pill',
    description: 'Bitter, chalky, and your heart races for an hour.',
    cost: 40,
    satiety: 10,
    energy: 30,
    slots: 0,
  },
  {
    id: 'hanami-dango',
    icon: 'dango',
    name: 'Hanami Dango',
    description: 'Pink, white and green, eaten under the blossoms.',
    cost: 10,
    satiety: 15,
    energy: 15,
    slots: 0,
  },
  {
    id: 'takoyaki',
    icon: 'bowl',
    name: 'Takoyaki',
    description: 'Octopus balls from a stall by the river, hot enough to hurt.',
    cost: 18,
    satiety: 30,
    energy: 10,
    slots: 0,
  },
  {
    id: 'shaved-ice',
    icon: 'tea',
    name: 'Shaved Ice',
    description: 'Strawberry syrup over a mountain of ice. Instant brain freeze.',
    cost: 8,
    satiety: 5,
    energy: 20,
    slots: 0,
  },
  {
    id: 'festival-yakisoba',
    icon: 'bowl',
    name: 'Festival Yakisoba',
    description: 'Fried noodles piled high on a paper plate.',
    cost: 15,
    satiety: 35,
    energy: 10,
    slots: 0,
  },
  {
    id: 'toshikoshi-soba',
    icon: 'bowl',
    name: 'Year-Crossing Soba',
    description: 'Long noodles for a long life, eaten before midnight.',
    cost: 12,
    satiety: 30,
    energy: 15,
    slots: 0,
  },
];
