import type { GearDef } from '../../types';

/** What the forge and the outfitter sell. Bonuses apply in fights while equipped. */
export const GEAR: readonly GearDef[] = [
  {
    id: 'fingerless-gloves',
    name: 'Fingerless Gloves',
    description: 'Reinforced knuckles under worn leather. Lee swears by them.',
    slot: 'weapon',
    cost: 120,
    icon: 'fist',
    statBonuses: { taijutsu: 2 },
  },
  {
    id: 'tanto',
    name: 'Tantō',
    description: 'A short, straight blade. ANBU favour them for a reason.',
    slot: 'weapon',
    cost: 180,
    icon: 'sword',
    statBonuses: { kenjutsu: 2, speed: 1 },
  },
  {
    id: 'sealing-brush',
    name: 'Sealing Brush',
    description: 'A fine brush and chakra-infused ink for writing seals at speed.',
    slot: 'weapon',
    cost: 200,
    icon: 'seal',
    statBonuses: { fuuinjutsu: 3 },
  },
  {
    id: 'genjutsu-bell',
    name: 'Genjutsu Bell',
    description: 'A small bell whose ring carries an illusion straight into the ear.',
    slot: 'weapon',
    cost: 200,
    icon: 'charm',
    statBonuses: { genjutsu: 2, perception: 1 },
  },
  {
    id: 'trench-knives',
    name: 'Chakra Trench Knives',
    description: 'Knuckle blades that channel wind chakra along the edge.',
    slot: 'weapon',
    cost: 300,
    icon: 'fist',
    statBonuses: { taijutsu: 2, ninjutsu: 2 },
  },
  {
    id: 'katana',
    name: 'Katana',
    description: 'A proper sword from the best smith in the Land of Fire.',
    slot: 'weapon',
    cost: 380,
    icon: 'sword',
    statBonuses: { kenjutsu: 3, strength: 1 },
  },
  {
    id: 'mesh-shirt',
    name: 'Mesh Armour Shirt',
    description: 'Chain mesh under your clothes. Standard issue, for a reason.',
    slot: 'body',
    cost: 90,
    icon: 'vest',
    statBonuses: { stamina: 1 },
  },
  {
    id: 'shadow-cloak',
    name: 'Shadow Cloak',
    description: 'A dark travelling cloak for night work.',
    slot: 'body',
    cost: 240,
    icon: 'vest',
    statBonuses: { speed: 2, perception: 1 },
  },
  {
    id: 'flak-vest',
    name: 'Flak Vest',
    description: 'The green vest of the Leaf. Pockets for everything.',
    slot: 'body',
    cost: 260,
    icon: 'vest',
    statBonuses: { stamina: 3 },
  },
  {
    id: 'prayer-beads',
    name: 'Prayer Beads',
    description: 'Worn smooth by a monk’s hands. Steadies the mind against fear.',
    slot: 'charm',
    cost: 150,
    icon: 'charm',
    statBonuses: { willpower: 2 },
  },
  {
    id: 'hawk-talisman',
    name: 'Hawk-Eye Talisman',
    description: 'A feather bound in red thread. You notice things a moment sooner.',
    slot: 'charm',
    cost: 180,
    icon: 'eye',
    statBonuses: { perception: 2 },
  },
  {
    id: 'chakra-paper-charm',
    name: 'Chakra Paper Charm',
    description: 'A folded slip of chakra paper. Helps keep your flow steady.',
    slot: 'charm',
    cost: 220,
    icon: 'charm',
    statBonuses: { chakraControl: 2 },
  },
];
