import { look } from '../../look';
import type { PersonDef } from '../../types';

/** The genin of your graduating year and the year above. Friends, rivals, nuisances. */
export const CANON_GENIN: readonly PersonDef[] = [
  {
    id: 'naruto',
    name: 'Naruto',
    familyName: 'Uzumaki',
    role: 'genin',
    title: 'Genin',
    clanId: 'uzumaki',
    traitIds: ['brash', 'kind'],
    favouriteRecipeId: 'miso-soup',
    appearance: look('spiky', {
      hair: '#e0b64a',
      eyes: '#3b6fb6',
      skin: '#e2b48c',
      outfit: '#e8823a',
    }),
    specialty: 'ninjutsu',
    bio: 'Loud, stubborn and impossible to discourage. Says he will be Hokage. Eats only ramen.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'mission-desk',
      evening: 'shopping-district',
      night: null,
    },
  },
  {
    id: 'sasuke',
    name: 'Sasuke',
    familyName: 'Uchiha',
    role: 'genin',
    title: 'Genin',
    clanId: 'uchiha',
    traitIds: ['proud', 'focused'],
    favouriteRecipeId: 'grilled-fish-set',
    appearance: look('spiky', {
      hair: '#1b1a22',
      eyes: '#2a1d14',
      skin: '#f3d2b3',
      outfit: '#2f4f7a',
    }),
    specialty: 'ninjutsu',
    bio: 'Top of the class and knows it. Trains alone. Talks less than he should.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'training-grounds',
      evening: null,
      night: null,
    },
  },
  {
    id: 'sakura',
    name: 'Sakura',
    familyName: 'Haruno',
    role: 'genin',
    title: 'Genin',
    traitIds: ['diligent', 'proud'],
    favouriteRecipeId: 'rice-ball-bento',
    appearance: look('long', {
      hair: '#d8789a',
      eyes: '#4f8a3a',
      skin: '#f3d2b3',
      outfit: '#9a2f2a',
    }),
    specialty: 'genjutsu',
    bio: 'Best written exam scores in years and perfect chakra control. Will not be underestimated.',
    schedule: {
      morning: 'academy',
      afternoon: 'training-grounds',
      evening: 'shopping-district',
      night: null,
    },
  },
  {
    id: 'hinata',
    name: 'Hinata',
    familyName: 'Hyūga',
    role: 'genin',
    title: 'Genin',
    clanId: 'hyuga',
    traitIds: ['kind', 'humble'],
    favouriteRecipeId: 'spicy-hot-pot',
    appearance: look(
      'long',
      { hair: '#3d5fa8', eyes: '#c9c3d9', skin: '#f3d2b3', outfit: '#e8e0d0' },
      'neck',
    ),
    specialty: 'taijutsu',
    bio: 'Quiet, gentle, and much stronger than her clan gives her credit for.',
    schedule: { morning: 'training-grounds', afternoon: 'academy', evening: null, night: null },
  },
  {
    id: 'kiba',
    name: 'Kiba',
    familyName: 'Inuzuka',
    role: 'genin',
    title: 'Genin',
    clanId: 'inuzuka',
    traitIds: ['brash', 'proud'],
    appearance: look('spiky', {
      hair: '#4a2f1d',
      eyes: '#2a1d14',
      skin: '#c68e63',
      outfit: '#2a2a32',
    }),
    specialty: 'taijutsu',
    bio: 'Never seen without Akamaru on his head. Picks fights he’s sure he can win.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'shopping-district',
      evening: 'training-grounds',
      night: 'izakaya',
    },
  },
  {
    id: 'shino',
    name: 'Shino',
    familyName: 'Aburame',
    role: 'genin',
    title: 'Genin',
    clanId: 'aburame',
    traitIds: ['calm', 'focused'],
    appearance: look('short', {
      hair: '#2a2a32',
      eyes: '#2a2a32',
      skin: '#e2b48c',
      outfit: '#3e6b3a',
    }),
    specialty: 'ninjutsu',
    bio: 'Speaks in complete, logical sentences. Remembers every slight. Carries a colony.',
    schedule: { morning: 'academy', afternoon: 'training-grounds', evening: null, night: null },
  },
  {
    id: 'shikamaru',
    name: 'Shikamaru',
    familyName: 'Nara',
    role: 'genin',
    title: 'Genin',
    clanId: 'nara',
    traitIds: ['lazy', 'cunning'],
    appearance: look(
      'ponytail',
      { hair: '#1b1a22', eyes: '#2a1d14', skin: '#e2b48c', outfit: '#3e6b3a' },
      'arm',
    ),
    specialty: 'ninjutsu',
    bio: 'Genius, if he could be bothered. Would rather watch clouds than do almost anything.',
    schedule: {
      morning: null,
      afternoon: 'training-grounds',
      evening: 'shopping-district',
      night: null,
    },
  },
  {
    id: 'choji',
    name: 'Chōji',
    familyName: 'Akimichi',
    role: 'genin',
    title: 'Genin',
    clanId: 'akimichi',
    traitIds: ['kind', 'humble'],
    appearance: look('spiky', {
      hair: '#8a5a2b',
      eyes: '#2a1d14',
      skin: '#f3d2b3',
      outfit: '#3e6b3a',
    }),
    specialty: 'taijutsu',
    bio: 'Big-hearted, loyal, and always holding a bag of chips. Do not call him fat.',
    schedule: {
      morning: 'shopping-district',
      afternoon: 'training-grounds',
      evening: 'shopping-district',
      night: null,
    },
  },
  {
    id: 'ino',
    name: 'Ino',
    familyName: 'Yamanaka',
    role: 'genin',
    title: 'Genin',
    clanId: 'yamanaka',
    traitIds: ['proud', 'curious'],
    appearance: look(
      'ponytail',
      { hair: '#e0b64a', eyes: '#3b6fb6', skin: '#f3d2b3', outfit: '#5a3a6e' },
      'belt',
    ),
    specialty: 'genjutsu',
    bio: 'Knows everyone’s business by lunchtime. Works the family flower shop when she has to.',
    schedule: {
      morning: 'shopping-district',
      afternoon: 'mission-desk',
      evening: 'shopping-district',
      night: null,
    },
  },
  {
    id: 'lee',
    name: 'Rock',
    familyName: 'Lee',
    role: 'genin',
    title: 'Genin',
    traitIds: ['diligent', 'brash'],
    appearance: look(
      'short',
      { hair: '#1b1a22', eyes: '#2a1d14', skin: '#f3d2b3', outfit: '#3e6b3a' },
      'belt',
    ),
    specialty: 'taijutsu',
    bio: 'Cannot use ninjutsu or genjutsu at all. Has decided this will not stop him.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'training-grounds',
      evening: 'training-grounds',
      night: null,
    },
  },
  {
    id: 'neji',
    name: 'Neji',
    familyName: 'Hyūga',
    role: 'genin',
    title: 'Genin',
    clanId: 'hyuga',
    traitIds: ['proud', 'calm'],
    appearance: look('long', {
      hair: '#2a1d14',
      eyes: '#c9c3d9',
      skin: '#f3d2b3',
      outfit: '#e8e0d0',
    }),
    specialty: 'taijutsu',
    bio: 'A branch-house prodigy who believes fate is decided at birth. Rarely wrong in a fight.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'training-grounds',
      evening: null,
      night: null,
    },
  },
  {
    id: 'tenten',
    name: 'Tenten',
    familyName: '',
    role: 'genin',
    title: 'Genin',
    traitIds: ['focused', 'kind'],
    appearance: look('buns', {
      hair: '#4a2f1d',
      eyes: '#4a2f1d',
      skin: '#f3d2b3',
      outfit: '#d8789a',
    }),
    specialty: 'kenjutsu',
    bio: 'Never misses with a thrown weapon. Has a scroll for every blade ever made.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'shopping-district',
      evening: 'training-grounds',
      night: null,
    },
  },
];
