import type { MissionDef } from '@/systems/missions';

export const MISSIONS: readonly MissionDef[] = [
  {
    id: 'border-patrol',
    title: 'Village Border Patrol',
    rank: 'D',
    client: 'Konoha Gate Guard',
    summary: 'Walk the inner border of the village woods and report anything odd. Always needed.',
    slots: 2,
    energyCost: 15,
    reward: { ryo: 55, reputation: 1 },
    minMissionsCompleted: 0,
    standing: true,
    stages: [
      {
        kind: 'narrative',
        text: 'Kotetsu and Izumo wave you through the gate with a map and a yawn.',
      },
      {
        kind: 'check',
        text: 'Deep in the woods, you find fresh tracks that don’t belong to any Leaf shinobi.',
        approaches: [
          { label: 'Follow the tracks carefully', stat: 'perception', difficulty: 7 },
          { label: 'Race back and report them', stat: 'speed', difficulty: 7 },
        ],
        success: 'The tracks lead to a lost merchant. You guide him back to the road.',
        failure: 'You lose the trail in a stream and come back empty-handed and soaked.',
        onFailure: 'penalty',
        failureDamage: 2,
      },
    ],
  },
  {
    id: 'catch-tora',
    title: 'Catch Tora the Cat',
    rank: 'D',
    client: 'Madam Shijimi',
    summary: 'The Fire Daimyō’s wife has lost her cat. Again.',
    slots: 2,
    energyCost: 15,
    reward: { ryo: 90, reputation: 3 },
    minMissionsCompleted: 0,
    stages: [
      {
        kind: 'narrative',
        text: 'Madam Shijimi dabs at her eyes. "My poor Tora. She has a ribbon on her left ear."',
      },
      {
        kind: 'check',
        text: 'A flash of brown fur and a red ribbon vanishes into the forest at the edge of the training grounds.',
        approaches: [
          { label: 'Chase her down', stat: 'speed', difficulty: 7 },
          { label: 'Track her trail', stat: 'perception', difficulty: 8 },
        ],
        success: 'You pin Tora in a bush. She scratches your face, as is tradition.',
        failure: 'Tora leads you on a two-hour chase before you finally corner her.',
        onFailure: 'penalty',
        failureDamage: 3,
      },
    ],
  },
  {
    id: 'yamanaka-weeding',
    title: 'Weeding at the Yamanaka Flower Shop',
    rank: 'D',
    client: 'Yamanaka Flowers',
    summary: 'The back greenhouse is overgrown, and the staff say something in there whispers.',
    slots: 3,
    energyCost: 25,
    reward: { ryo: 110, reputation: 3 },
    minMissionsCompleted: 0,
    stages: [
      {
        kind: 'check',
        text: 'The weeds are waist-high, and something under the old pots keeps whispering your name.',
        approaches: [
          { label: 'Work through the backache', stat: 'stamina', difficulty: 7 },
          { label: 'Ignore the whispers', stat: 'willpower', difficulty: 8 },
        ],
        success: 'By dusk the greenhouse is spotless. The whispering stops, as if satisfied.',
        failure: 'You finish, but Ino has to redo a corner you abandoned in a cold sweat.',
        onFailure: 'penalty',
      },
    ],
  },
  {
    id: 'farm-medicine',
    title: 'Medicine for the Outer Farms',
    rank: 'D',
    client: 'Konoha Hospital',
    summary: 'Carry fever medicine to a farm outside the walls before nightfall.',
    slots: 3,
    energyCost: 25,
    reward: { ryo: 150, reputation: 4 },
    minMissionsCompleted: 1,
    stages: [
      {
        kind: 'check',
        text: 'The farm is a long way out past the rice paddies.',
        approaches: [
          { label: 'Run the whole way', stat: 'stamina', difficulty: 8 },
          { label: 'Take the treetop route', stat: 'speed', difficulty: 9 },
        ],
        success: 'You make excellent time, branch to branch.',
        failure: 'You arrive late and mud-soaked. The farmer is not impressed.',
        onFailure: 'penalty',
      },
      {
        kind: 'combat',
        text: 'A wild boar has been raiding the storehouse, and it does not want to share.',
        enemyIds: ['wild-boar'],
        canFlee: true,
      },
      {
        kind: 'narrative',
        text: 'The farmer’s daughter is already sitting up by the time you leave.',
      },
    ],
  },
  {
    id: 'merchant-escort',
    title: 'Escort a Merchant to Tanzaku Town',
    rank: 'D',
    client: 'Merchant Ōkubo',
    summary: 'See a nervous tea merchant safely to the Tanzaku Town road.',
    slots: 4,
    energyCost: 30,
    reward: { ryo: 220, reputation: 6 },
    minMissionsCompleted: 2,
    stages: [
      { kind: 'narrative', text: 'Ōkubo talks about tea prices for the entire first hour.' },
      {
        kind: 'check',
        text: 'The road narrows between two rocky banks. Something feels wrong.',
        approaches: [
          { label: 'Scan the ridgeline', stat: 'perception', difficulty: 9 },
          { label: 'Recall where ambushes happen', stat: 'intellect', difficulty: 10 },
        ],
        success: 'You spot the bandit before he springs his ambush.',
        failure: 'A rock catches you on the shoulder as the bandit leaps down.',
        onFailure: 'penalty',
        failureDamage: 10,
      },
      {
        kind: 'combat',
        text: '"Leave the cart and walk away, kid."',
        enemyIds: ['bandit-thug'],
        canFlee: false,
      },
    ],
  },
  {
    id: 'stolen-scrolls',
    title: 'The Stolen Practice Scrolls',
    rank: 'D',
    client: 'Iruka Umino',
    summary: 'A washed-out academy student has been stealing practice scrolls. Bring him in.',
    slots: 3,
    energyCost: 25,
    reward: { ryo: 200, reputation: 5 },
    minMissionsCompleted: 2,
    stages: [
      {
        kind: 'check',
        text: 'Iruka-sensei hands you a list of the missing scrolls. Where would he go to practise them?',
        approaches: [
          { label: 'Follow the scorch marks', stat: 'perception', difficulty: 9 },
          { label: 'Think like a dropout', stat: 'intellect', difficulty: 9 },
        ],
        success: 'You find him in the woods behind the academy, mid-seal.',
        failure: 'By the time you find him, he has heard you coming.',
        onFailure: 'penalty',
      },
      {
        kind: 'combat',
        text: '"You think a headband makes you better than me?"',
        enemyIds: ['academy-dropout'],
        canFlee: true,
      },
    ],
  },
  {
    id: 'haunted-granary',
    title: 'The Haunted Granary',
    rank: 'D',
    client: 'Akimichi Grain Store',
    summary: 'Something is spoiling the grain, and the workers refuse to go inside.',
    slots: 3,
    energyCost: 30,
    reward: { ryo: 260, reputation: 8 },
    minMissionsCompleted: 3,
    stages: [
      {
        kind: 'check',
        text: 'The granary is freezing. Ledgers flip their own pages. The lamp keeps going out.',
        approaches: [
          { label: 'Steel your nerves and go in', stat: 'willpower', difficulty: 10 },
          { label: 'Release the illusion', stat: 'genjutsu', difficulty: 10 },
        ],
        success: 'You walk straight to the back wall, where the cold is strongest.',
        failure: 'You flee into the street before you realise you have moved. You go back in.',
        onFailure: 'penalty',
        failureDamage: 6,
      },
      {
        kind: 'combat',
        text: 'A grey figure rises from the grain sacks. "Mine. All of it. Mine."',
        enemyIds: ['restless-spirit'],
        canFlee: false,
      },
      {
        kind: 'narrative',
        text: 'You light incense at the door. The cold drains away, and the grain smells sweet again.',
      },
    ],
  },
];
