import { allDay, look } from '../../look';
import type { PersonDef } from '../../types';

/** Jōnin who may take on a team, plus the village figures every genin knows. */
export const SENSEIS_AND_ELDERS: readonly PersonDef[] = [
  {
    id: 'kakashi',
    name: 'Kakashi',
    familyName: 'Hatake',
    role: 'sensei',
    title: 'Jōnin',
    traitIds: ['calm', 'lazy'],
    appearance: look('spiky', {
      hair: '#e8e0d0',
      eyes: '#2a1d14',
      skin: '#f3d2b3',
      outfit: '#2f4f7a',
    }),
    specialty: 'ninjutsu',
    bio: 'The Copy Ninja. Always late, always reading, never actually unaware of anything.',
    schedule: {
      morning: null,
      afternoon: 'training-grounds',
      evening: 'mission-desk',
      night: null,
    },
    sensei: {
      specialty: 'ninjutsu',
      favouredTraits: ['calm', 'cunning', 'focused'],
      nature: 'lightning',
      style: 'Late, lazy-looking, and misses nothing. Teaches teamwork the hard way.',
      lesson:
        'Kakashi turns up late, closes his book, and runs you ragged through every drill you thought you knew.',
      teaches: ['summoning-ninken', 'lightning-blade'],
    },
  },
  {
    id: 'guy',
    name: 'Might Guy',
    familyName: '',
    role: 'sensei',
    title: 'Jōnin',
    traitIds: ['brash', 'diligent'],
    appearance: look(
      'short',
      { hair: '#1b1a22', eyes: '#2a1d14', skin: '#e2b48c', outfit: '#3e6b3a' },
      'belt',
    ),
    specialty: 'taijutsu',
    bio: 'The Green Beast of the Hidden Leaf. Believes in hard work, youth, and five hundred laps.',
    schedule: {
      morning: 'training-grounds',
      afternoon: 'training-grounds',
      evening: 'shopping-district',
      night: null,
    },
    sensei: {
      specialty: 'taijutsu',
      favouredTraits: ['brash', 'diligent', 'proud'],
      style: 'Shouts, runs, and never lets you quit. Ever.',
      lesson:
        'Guy has you running laps on your hands before breakfast. He does twice as many, cheering.',
      teaches: ['leaf-hurricane', 'front-lotus'],
    },
  },
  {
    id: 'kurenai',
    name: 'Kurenai',
    familyName: 'Yūhi',
    role: 'sensei',
    title: 'Jōnin',
    traitIds: ['calm', 'kind'],
    appearance: look('long', {
      hair: '#1b1a22',
      eyes: '#b8322c',
      skin: '#f3d2b3',
      outfit: '#9a2f2a',
    }),
    specialty: 'genjutsu',
    bio: 'The village’s finest genjutsu user. Patient, precise, and protective of her students.',
    schedule: {
      morning: 'academy',
      afternoon: 'training-grounds',
      evening: 'shopping-district',
      night: null,
    },
    sensei: {
      specialty: 'genjutsu',
      favouredTraits: ['calm', 'kind', 'humble'],
      style: 'Patient and precise. Builds confidence before she builds technique.',
      lesson:
        'Kurenai walks you through an illusion slowly, then again, until you can see the seams.',
      teaches: ['petal-storm'],
    },
  },
  {
    id: 'asuma',
    name: 'Asuma',
    familyName: 'Sarutobi',
    role: 'sensei',
    title: 'Jōnin',
    traitIds: ['lazy', 'kind'],
    appearance: look('short', {
      hair: '#1b1a22',
      eyes: '#2a1d14',
      skin: '#e2b48c',
      outfit: '#2f4f7a',
    }),
    specialty: 'kenjutsu',
    bio: 'The Third Hokage’s son. Fights with wind-wrapped trench knives and a cigarette.',
    schedule: {
      morning: null,
      afternoon: 'shopping-district',
      evening: 'mission-desk',
      night: null,
    },
    sensei: {
      specialty: 'kenjutsu',
      favouredTraits: ['lazy', 'cunning', 'kind'],
      nature: 'wind',
      style: 'Easy-going until it matters. Teaches through shōgi as much as sparring.',
      lesson:
        'Asuma teaches you to feel the wind along a blade, then beats you at shōgi to make a point.',
      teaches: ['flying-swallow'],
    },
  },
  {
    id: 'anko',
    name: 'Anko',
    familyName: 'Mitarashi',
    role: 'sensei',
    title: 'Special Jōnin',
    traitIds: ['brash', 'curious'],
    appearance: look('ponytail', {
      hair: '#5a3a6e',
      eyes: '#7a4a8a',
      skin: '#f3d2b3',
      outfit: '#2a2a32',
    }),
    specialty: 'fuuinjutsu',
    bio: 'Snake techniques, a cursed seal, and a fondness for dango. Terrifying examiner.',
    schedule: {
      morning: 'shopping-district',
      afternoon: 'training-grounds',
      evening: null,
      night: null,
    },
    sensei: {
      specialty: 'fuuinjutsu',
      favouredTraits: ['brash', 'curious', 'cunning'],
      style: 'Throws you in the deep end, then throws snakes in after you.',
      lesson:
        'Anko chases you through the training forest with snakes until your seals come out clean.',
      teaches: ['snake-binding-seal'],
    },
  },
  {
    id: 'iruka',
    name: 'Iruka',
    familyName: 'Umino',
    role: 'instructor',
    title: 'Academy instructor',
    traitIds: ['kind', 'diligent'],
    appearance: look('ponytail', {
      hair: '#4a2f1d',
      eyes: '#2a1d14',
      skin: '#c68e63',
      outfit: '#2f4f7a',
    }),
    bio: 'Taught you everything you know. Hands out missions in the afternoons. Pays for ramen too often.',
    schedule: {
      morning: 'academy',
      afternoon: 'mission-desk',
      evening: 'shopping-district',
      night: null,
    },
  },
  {
    id: 'hiruzen',
    name: 'Hiruzen',
    familyName: 'Sarutobi',
    role: 'leader',
    title: 'Third Hokage',
    traitIds: ['kind', 'calm'],
    appearance: look(
      'shaved',
      { hair: '#e8e0d0', eyes: '#2a1d14', skin: '#e2b48c', outfit: '#e8e0d0' },
      'arm',
    ),
    bio: 'The Professor. Leads the village from behind a pipe and a mountain of paperwork.',
    schedule: { morning: 'mission-desk', afternoon: null, evening: null, night: null },
  },
  {
    id: 'teuchi',
    name: 'Teuchi',
    familyName: '',
    role: 'villager',
    title: 'Ramen chef',
    traitIds: ['kind', 'focused'],
    appearance: look(
      'shaved',
      { hair: '#8a5a2b', eyes: '#2a1d14', skin: '#e2b48c', outfit: '#e8e0d0' },
      'arm',
    ),
    bio: 'Owner of Ichiraku Ramen. Has fed every hungry genin in the village at least once.',
    schedule: allDay('shopping-district'),
  },
  {
    id: 'ayame',
    name: 'Ayame',
    familyName: '',
    role: 'villager',
    title: 'Ichiraku Ramen',
    traitIds: ['kind', 'curious'],
    appearance: look(
      'long',
      { hair: '#4a2f1d', eyes: '#2a1d14', skin: '#f3d2b3', outfit: '#e8e0d0' },
      'arm',
    ),
    bio: 'Teuchi’s daughter. Knows every regular’s order and most of their secrets.',
    schedule: {
      morning: null,
      afternoon: 'shopping-district',
      evening: 'shopping-district',
      night: null,
    },
  },
];
