import type { TechniqueDef } from '@/systems/techniques';

/** Signature techniques only a sensei can teach, at their weekly lessons. */
export const SENSEI_TECHNIQUES: readonly TechniqueDef[] = [
  {
    id: 'summoning-ninken',
    name: 'Summoning: Ninken Pack',
    description: 'Eight tracking dogs burst from the ground and pin the target in place.',
    discipline: 'ninjutsu',
    effect: 'stun',
    chakraCost: 12,
    power: 16,
    requirements: {},
    difficulty: 60,
  },
  {
    id: 'lightning-blade',
    name: 'Lightning Blade',
    description: 'Chakra gathered in one hand until it shrieks like a thousand birds.',
    discipline: 'ninjutsu',
    element: 'lightning',
    effect: 'damage',
    chakraCost: 18,
    power: 26,
    requirements: {},
    difficulty: 100,
  },
  {
    id: 'leaf-hurricane',
    name: 'Leaf Hurricane',
    description: 'Konoha Daisenpū. A spinning kick chain that does not stop until you do.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 8,
    power: 19,
    requirements: {},
    difficulty: 60,
  },
  {
    id: 'front-lotus',
    name: 'Front Lotus',
    description: 'Kick them skyward, wrap them up, and drive them into the ground. Hurts you too.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 14,
    power: 27,
    requirements: {},
    difficulty: 100,
  },
  {
    id: 'petal-storm',
    name: 'Demonic Illusion: Petal Storm',
    description: 'A whirl of petals the target can’t stop watching, until it’s too late.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 12,
    power: 18,
    requirements: {},
    difficulty: 70,
  },
  {
    id: 'flying-swallow',
    name: 'Flying Swallow',
    description: 'Wind chakra lengthens your blade’s edge beyond the steel.',
    discipline: 'kenjutsu',
    element: 'wind',
    effect: 'damage',
    chakraCost: 10,
    power: 21,
    requirements: {},
    difficulty: 70,
  },
  {
    id: 'snake-binding-seal',
    name: 'Snake Binding Seal',
    description: 'Ink snakes coil over the target’s chakra points and squeeze them shut.',
    discipline: 'fuuinjutsu',
    effect: 'seal',
    chakraCost: 12,
    power: 16,
    requirements: {},
    difficulty: 70,
  },
];
