import type { TechniqueDef } from '@/systems/techniques';

export const TECHNIQUES: readonly TechniqueDef[] = [
  {
    id: 'shuriken-jutsu',
    name: 'Shuriken Jutsu',
    description: 'A practised flick of the wrist. Every academy student learns it first.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 3,
    power: 8,
    requirements: {},
    difficulty: 20,
  },
  {
    id: 'clone-jutsu',
    name: 'Clone Jutsu',
    description: 'Illusory copies that leave the enemy swinging at nothing.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 6,
    power: 6,
    requirements: {},
    difficulty: 20,
  },
  {
    id: 'leaf-whirlwind',
    name: 'Leaf Whirlwind',
    description: 'Konoha Senpū. A low spinning kick that sweeps the legs out from under you.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 5,
    power: 13,
    requirements: { taijutsu: 8, speed: 7 },
    difficulty: 40,
  },
  {
    id: 'phoenix-flower',
    name: 'Fire Style: Phoenix Sage Fire',
    description: 'A volley of small fireballs, each hiding a shuriken.',
    discipline: 'ninjutsu',
    element: 'fire',
    effect: 'damage',
    chakraCost: 8,
    power: 12,
    requirements: { ninjutsu: 7 },
    difficulty: 40,
  },
  {
    id: 'hell-viewing',
    name: 'Demonic Illusion: Hell Viewing',
    description: 'Show the target the thing they fear most.',
    discipline: 'genjutsu',
    effect: 'stun',
    chakraCost: 10,
    power: 12,
    requirements: { genjutsu: 8, perception: 6 },
    difficulty: 45,
  },
  {
    id: 'leaf-rising-wind',
    name: 'Leaf Rising Wind',
    description: 'Konoha Shōfū. A rising kick that launches the enemy into the air.',
    discipline: 'taijutsu',
    effect: 'damage',
    chakraCost: 7,
    power: 18,
    requirements: { taijutsu: 12, strength: 10 },
    difficulty: 70,
  },
  {
    id: 'great-fireball',
    name: 'Fire Style: Great Fireball',
    description: 'Mould chakra in the lungs and breathe out a roaring sphere of flame.',
    discipline: 'ninjutsu',
    element: 'fire',
    effect: 'damage',
    chakraCost: 12,
    power: 18,
    requirements: { ninjutsu: 10, chakraControl: 8 },
    difficulty: 70,
  },
  {
    id: 'water-bullet',
    name: 'Water Style: Water Bullet',
    description: 'Spit a pressurised ball of water hard enough to crack stone.',
    discipline: 'ninjutsu',
    element: 'water',
    effect: 'damage',
    chakraCost: 15,
    power: 22,
    requirements: { ninjutsu: 13, chakraControl: 11 },
    difficulty: 90,
  },
  {
    id: 'tree-binding',
    name: 'Demonic Illusion: Tree Binding',
    description: 'Roots that are not there bind the target while you strike.',
    discipline: 'genjutsu',
    effect: 'damage',
    chakraCost: 11,
    power: 16,
    requirements: { genjutsu: 11, willpower: 9 },
    difficulty: 75,
  },
  {
    id: 'mystical-palm',
    name: 'Mystical Palm Technique',
    description: 'The medical ninja’s green glow, closing wounds from the inside.',
    discipline: 'ninjutsu',
    effect: 'heal',
    chakraCost: 12,
    power: 18,
    requirements: { chakraControl: 9, intellect: 8 },
    difficulty: 60,
  },
];
