import type { TrainingDef } from '../../types';

export const TRAINING: readonly TrainingDef[] = [
  {
    id: 'training-posts',
    name: 'Kicking the Posts',
    spot: 'Training Ground 3',
    icon: 'post',
    description: 'You hammer the three old posts until your shins stop complaining.',
    slots: 1,
    energyCost: 20,
    gains: { strength: 1, taijutsu: 1.2 },
  },
  {
    id: 'rooftop-runs',
    name: 'Rooftop Runs',
    spot: 'Village rooftops',
    icon: 'house',
    description: 'You race across the rooftops, leaping the gaps between houses.',
    slots: 1,
    energyCost: 20,
    gains: { speed: 1.5, stamina: 0.5 },
  },
  {
    id: 'wall-laps',
    name: 'Laps of the Village Walls',
    spot: 'The great gates',
    icon: 'wave',
    description:
      'One lap, then another, the gate guards cheering you on with less enthusiasm each time.',
    slots: 1,
    energyCost: 25,
    gains: { stamina: 1.5, willpower: 0.5 },
  },
  {
    id: 'tree-climbing',
    name: 'Tree Climbing Practice',
    spot: 'Training Ground 7',
    icon: 'tree',
    description: 'No hands. Chakra to the soles of your feet, and up the trunk you go.',
    slots: 1,
    energyCost: 10,
    gains: { chakraControl: 1.5, willpower: 0.3 },
  },
  {
    id: 'seal-drills',
    name: 'Hand-Seal Drills',
    spot: 'Academy yard',
    icon: 'scroll',
    description: 'Boar, dog, bird, monkey, ram. Faster and faster until they blur.',
    slots: 1,
    energyCost: 15,
    gains: { ninjutsu: 1.5, chakraControl: 0.5 },
  },
  {
    id: 'library-study',
    name: 'Scroll Study',
    spot: 'Academy library',
    icon: 'scroll',
    description: 'You pore over strategy scrolls until the librarian turns the lamps down.',
    slots: 1,
    energyCost: 8,
    gains: { intellect: 1.5, genjutsu: 0.4 },
  },
  {
    id: 'illusion-spotting',
    name: 'Illusion Spotting',
    spot: 'Training Ground 8',
    icon: 'eye',
    description: 'Disrupt your own chakra flow, again and again, until false things look false.',
    slots: 1,
    energyCost: 10,
    gains: { perception: 1.5, genjutsu: 0.8 },
  },
  {
    id: 'waterfall-meditation',
    name: 'Waterfall Meditation',
    spot: 'Falls outside the village',
    icon: 'wave',
    description: 'You sit beneath freezing water and refuse to move.',
    slots: 1,
    energyCost: 25,
    gains: { willpower: 1.5, stamina: 0.5 },
  },
  {
    id: 'youth-sparring',
    name: 'Sparring with Team Guy',
    spot: 'Training Ground 3',
    icon: 'fist',
    description: 'Guy-sensei shouts about the power of youth while Lee refuses to stay down.',
    slots: 1,
    energyCost: 30,
    gains: { taijutsu: 1, speed: 0.5, strength: 0.5, perception: 0.5 },
  },
  {
    id: 'sword-kata',
    name: 'Sword Kata',
    spot: 'Training Ground 3',
    icon: 'sword',
    description: 'Draw, cut, sheathe. A thousand times, until the blade feels like your arm.',
    slots: 1,
    energyCost: 20,
    gains: { kenjutsu: 1.5, speed: 0.3 },
  },
  {
    id: 'seal-calligraphy',
    name: 'Seal Calligraphy',
    spot: 'Academy library',
    icon: 'seal',
    description: 'Brush, ink and patience. One wrong stroke and the seal is useless.',
    slots: 1,
    energyCost: 10,
    gains: { fuuinjutsu: 1.5, chakraControl: 0.3 },
  },
];
