import type { LocationDef, SettingText } from '../../types';

export const NARUTO_TEXT: SettingText = {
  nation: 'the Land of Fire',
  leaderTitle: 'Hokage',
  currency: 'ryo',
  intro:
    'The Hidden Leaf sits deep in the forests of the Land of Fire, watched over by the faces ' +
    'carved into the Hokage Rock. Spirits walk the old roads, and the elements answer to ' +
    'those who listen. Today you tied on your forehead protector for the first time.',
  graduate: 'Tie on your forehead protector',
  sleepWell: 'You sleep soundly. Somewhere a cicada keeps time.',
  sleepHungry: 'You sleep fitfully on an empty stomach.',
  sleepLockedOut: 'Your landlady has locked the door over unpaid rent. You sleep on the stairs.',
  hospitalWake: 'You wake in Konoha Hospital, under clean sheets and a medic’s frown.',
};

export const NARUTO_LOCATIONS: readonly LocationDef[] = [
  {
    id: 'konohagakure',
    name: 'Konohagakure',
    epithet: 'Village Hidden in the Leaves',
    backdrop: 'leaf-village',
    travel: { days: 0, cost: 0, danger: 'Home' },
    places: [
      {
        id: 'mission-desk',
        kind: 'missions',
        name: 'Mission Assignment Desk',
        icon: 'board',
        blurb: 'Iruka hands out D-ranks',
        missionIds: [
          'catch-tora',
          'yamanaka-weeding',
          'farm-medicine',
          'merchant-escort',
          'stolen-scrolls',
          'haunted-granary',
        ],
      },
      {
        id: 'training-grounds',
        kind: 'training',
        name: 'Training Grounds',
        icon: 'post',
        blurb: 'Posts, trees and the falls',
        trainingIds: [
          'training-posts',
          'rooftop-runs',
          'wall-laps',
          'tree-climbing',
          'seal-drills',
          'library-study',
          'illusion-spotting',
          'waterfall-meditation',
          'youth-sparring',
        ],
      },
      {
        id: 'shopping-district',
        kind: 'market',
        name: 'Shopping District',
        icon: 'bowl',
        blurb: 'Ichiraku is open',
        stalls: [
          {
            name: 'Ichiraku Ramen',
            blurb: 'Teuchi and Ayame',
            icon: 'bowl',
            foodIds: ['miso-ramen', 'pork-ramen'],
          },
          {
            name: 'Yakiniku Q',
            blurb: 'Barbecue, take your time',
            icon: 'grill',
            foodIds: ['yakiniku'],
          },
          { name: 'Amaguriama', blurb: 'Sweets and tea', icon: 'dango', foodIds: ['dango'] },
          {
            name: 'Konoha Pharmacy',
            blurb: 'Pills and salves',
            icon: 'pill',
            foodIds: ['soldier-pill'],
          },
        ],
      },
      {
        id: 'academy',
        kind: 'academy',
        name: 'Ninja Academy',
        icon: 'scroll',
        blurb: 'Library of techniques',
        techniqueIds: [
          'leaf-whirlwind',
          'phoenix-flower',
          'hell-viewing',
          'leaf-rising-wind',
          'great-fireball',
          'water-bullet',
          'tree-binding',
          'mystical-palm',
        ],
      },
      {
        id: 'apartment',
        kind: 'home',
        name: 'Your Apartment',
        icon: 'house',
        blurb: 'One room, one window',
        lodging: 'One-room apartment off the main street',
        rentPerWeek: 30,
      },
      {
        id: 'hospital',
        kind: 'hospital',
        name: 'Konoha Hospital',
        icon: 'heal',
        blurb: 'Medical ninja on call',
        treatmentCost: 60,
      },
    ],
  },
  {
    id: 'sunagakure',
    name: 'Sunagakure',
    epithet: 'Village Hidden in the Sand',
    backdrop: 'dunes',
    places: [],
    travel: { days: 3, cost: 120, danger: 'Desert heat', lockedReason: 'Coming soon' },
  },
  {
    id: 'kirigakure',
    name: 'Kirigakure',
    epithet: 'Village Hidden in the Mist',
    backdrop: 'mist',
    places: [],
    travel: { days: 4, cost: 150, danger: 'Hostile village', lockedReason: 'Coming soon' },
  },
  {
    id: 'land-of-waves',
    name: 'Land of Waves',
    epithet: 'Fishing islands and a great bridge',
    backdrop: 'coast',
    places: [],
    travel: { days: 2, cost: 40, danger: 'Bandits', lockedReason: 'Coming soon' },
  },
  {
    id: 'mount-myoboku',
    name: 'Mount Myōboku',
    epithet: 'Where the toads train sages',
    backdrop: 'mountain',
    places: [],
    travel: { days: 5, cost: 0, danger: 'Unknown', lockedReason: 'Needs a summoning contract' },
  },
];
